# -*- coding: utf-8 -*-
"""C1Project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mvm2whtB_aA1uOPA8XeyWnnRB1GP2635
"""

!pip install datasets
from datasets import load_dataset
dataset = load_dataset("amazon_polarity")  # Replace with actual dataset name if needed

def preprocess_function(examples):
    # Normalize text by converting to lowercase and removing special characters
    # Access the correct column name, e.g., 'content'
    examples['content'] = [text.lower() for text in examples['content']]
    return examples

tokenized_dataset = dataset.map(preprocess_function, batched=True)

from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=3)  # 3 sentiment labels: Positive, Negative, Neutral

def preprocess_function(examples):
    return tokenizer(examples["content"], truncation=True, padding=True)  # Changed "text" to "content"

tokenized_dataset = dataset.map(preprocess_function, batched=True)

from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    num_train_epochs=3,
    weight_decay=0.01,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
)

trainer.train()

results = trainer.evaluate()
print("Test Accuracy:", results['eval_accuracy'])