# -*- coding: utf-8 -*-
"""Project 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wv8UOd95a3pMyXLgD9eiCCjZ_LtVjspJ

# **Project: About Menu Functioning**
## By Ajay Sethuraman
## **Introduction**
This project is designed to demonstrate the use of recursion and functions through an interactive menu-driven Python program. The user will be able to perform tasks like calculating the factorial of a number, finding the nth Fibonacci number, and even drawing a recursive fractal pattern (optional). The program will be user-friendly, offering friendly prompts, error messages, and input validation.

**Step 1: Menu of Recursive Functions**

**Program Setup**

We will create a menu with options to perform different tasks. The user can select from the following options:

* Calculate the factorial of a number.
* Find the nth Fibonacci number.
* Draw a recursive fractal pattern (bonus).
* Exit.
"""

import turtle

# Main menu function
def main_menu():
    """Displays the menu and executes the appropriate function based on the user's choice."""
    while True:
        print("\nWelcome to the Recursive Artistry Program!")
        print("Choose an option:")
        print("1. Calculate Factorial")
        print("2. Find Fibonacci")
        print("3. Draw a Recursive Fractal")
        print("4. Exit")

        try:
            choice = int(input("Enter your choice (1-4): "))
            if choice == 1:
                # Factorial Calculation
                num = int(input("Enter a number to find its factorial: "))
                if num < 0:
                    print("Please enter a positive integer.")
                    continue
                print(f"The factorial of {num} is {factorial(num)}.")
            elif choice == 2:
                # Fibonacci Calculation
                n = int(input("Enter the position of the Fibonacci number: "))
                if n < 0:
                    print("Please enter a positive integer.")
                    continue
                print(f"The {n}th Fibonacci number is {fibonacci(n)}.")
            elif choice == 3:
                # Draw Recursive Fractal
                print("Drawing a simple fractal tree... 🌳")
                screen = turtle.Screen()
                screen.bgcolor("white")
                t = turtle.Turtle()
                t.left(90)
                t.speed(0)
                draw_tree(t, 100, 25, 6)
                screen.exitonclick()
            elif choice == 4:
                print("Exiting program. Goodbye!")
                break
            else:
                print("Invalid choice, please select a number between 1 and 4.")
        except ValueError:
            print("Invalid input. Please enter a valid number.")

"""**Step 2: Factorial Function**

The recursive function factorial(n) calculates the factorial of a given number. The base case for the recursion is when the number is 0 or 1, which both return 1. Otherwise, the function calls itself with n - 1 and multiplies the result by n.


"""

# Recursive function to calculate the factorial
def factorial(n):
    """Calculates the factorial of a number using recursion."""
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

"""**Step 3: Fibonacci Function**

The recursive function fibonacci(n) calculates the nth Fibonacci number. The base case is when n is 0 or 1, returning n itself. Otherwise, the function calls itself recursively to calculate the two preceding numbers and adds them together.
"""

# Recursive function to find the nth Fibonacci number
def fibonacci(n):
    """Calculates the nth Fibonacci number using recursion."""
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

"""**Step 4: Recursive Fractal Pattern (Bonus)**

The bonus part of the project involves using the turtle library to draw a recursive fractal pattern. We use the draw_tree(t, length, angle, level) function, which recursively draws branches of a tree. The base case occurs when the level is 0, stopping further recursion. The function uses the turtle to move forward, turn left, and draw two smaller branches in the opposite directions, creating the fractal tree.
"""

# Function to draw a recursive fractal pattern (e.g., tree)
def draw_tree(t, length, angle, level):
    """Draws a recursive fractal tree using turtle."""
    if level > 0:
        t.forward(length)
        t.left(angle)
        draw_tree(t, length * 0.7, angle, level - 1)
        t.right(2 * angle)
        draw_tree(t, length * 0.7, angle, level - 1)
        t.left(angle)
        t.backward(length)

"""The program has several user-friendly features:

* Input validation: Ensures the user enters positive integers for factorial and Fibonacci calculations.
* Error handling: If the user enters an invalid option or non-integer values, the program prompts them again.
* Friendly prompts: Clear and friendly messages guide the user through the program.
"""

if __name__ == "__main__":
    main_menu()

"""## **Conclusion**
This project demonstrates the power of recursion in Python through interactive menu choices. The recursive functions for factorial calculation, Fibonacci sequence generation, and fractal tree drawing showcase how recursion can be applied to real-world problems in a user-friendly, engaging way.
"""

