# -*- coding: utf-8 -*-
"""Project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TemeKWuUTTVqe-WRLFSk6kcuVsb2l8Qt

# **Number Guessing Game**
## By Ajay Sethuraman
## **Introduction**
This project is a fun number-guessing game where the user tries to guess a randomly generated number between 1 and 100. The game provides feedback on each guess and keeps track of attempts. There is also a challenge: the user has a maximum of 10 attempts to win.
"""

import random

# Generate a random number between 1 and 100
number_to_guess = random.randint(1, 100)

# Initializing variables
attempts = 0
max_attempts = 10

print("Welcome to the Number Guessing Game!")
print("Try to guess the number between 1 and 100. You have 10 attempts!")

# Loop for guessing
while attempts < max_attempts:
    guess = int(input("Enter your guess: "))  # Taking user input
    attempts += 1  # Increment attempts

    # Checking the guess
    if guess < number_to_guess:
        print("Too low! Try again.")
    elif guess > number_to_guess:
        print("Too high! Try again.")
    else:
        print(f"Congratulations! You guessed it in {attempts} attempts!")
        break  # Exit the loop if guessed correctly

# Game over message if max attempts reached
if attempts == max_attempts and guess != number_to_guess:
    print(f"Game over! The correct number was {number_to_guess}. Better luck next time!")

"""This project is an engaging and interactive way to practice loops, conditionals, and user input handling in Python."""

