# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSb_i6Z1s0T2Ql0LUVUzpPajH55vRvYw

# **Exploring Python Concepts**
## By Ajay Sethuraman
## **Introduction**
In this assignment, we will explore some fundamental Python concepts, such as variables, operators, and conditional statements. These concepts are the building blocks of programming, and mastering them will lay a solid foundation for more advanced topics. By the end of this assignment, you will be able to use variables to store data, perform operations on numbers, and write conditional statements to make decisions based on user input.
"""

# Creating variables to store personal information
name = "Ajay"  # String variable for name
age = 25  # Integer variable for age
height = 6.0  # Floating-point variable for height

# Printing a friendly message
print("Hey there, my name is", name + "!", "I’m", age, "years old and", height, "feet tall.")

"""* We created three variables: name, age, and height, each storing different types of data: string, integer, and float, respectively.
* The print() function is used to output a message that includes the values stored in these variables. By concatenating strings and numbers, we create a personalized message.




"""

# Defining two numbers
num1 = 10
num2 = 3

# Performing addition
print("The sum of", num1, "and", num2, "is", num1 + num2)

# Performing subtraction
print("The difference when", num2, "is subtracted from", num1, "is", num1 - num2)

# Performing multiplication
print("The product of", num1, "and", num2, "is", num1 * num2)

# Performing division
print("The division of", num1, "by", num2, "is", num1 / num2)

"""The two numbers num1 and num2 are assigned values of 10 and 3, respectively.
We then perform the four basic arithmetic operations:
* Addition: num1 + num2
* Subtraction: num1 - num2
* Multiplication: num1 * num2
* Division: num1 / num2
<br>Each result is printed with a clear message, explaining the operation being performed.
"""

# Taking user input
num = float(input("Enter a number: "))

# Checking if the number is positive, negative, or zero
if num > 0:
    print("This number is positive. Awesome!")
elif num < 0:
    print("This number is negative. Better luck next time!")
else:
    print("Zero it is. A perfect balance!")

"""The input() function is used to ask the user to enter a number. The float() function is used to convert the input into a floating-point number, as it can handle both integers and decimals.
<br>We use an if-elif-else statement to check the number:
* If the number is greater than 0, it prints "This number is positive. Awesome!".
* If the number is less than 0, it prints "This number is negative. Better luck next time!".
* If the number is exactly 0, it prints "Zero it is. A perfect balance!".

## **Conclusion**
In this assignment, I covered essential Python concepts, including variables, operators, and conditional statements. I created variables to store personal data and printed them in a friendly message. I also performed basic arithmetic operations and displayed the results with appropriate messages. Finally, I wrote a program that checks whether a user-input number is positive, negative, or zero using conditional statements. These concepts will serve as the foundation for more complex programming tasks.
"""

