# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkzTuUWJ3YfyNgyEtBKqGpJfxn_KHcw0

# **Capstone Project: Python-Based Employee Management System**
## By Ajay Sethuraman
## **Overview**
Title: Python-Based Employee Management System
Overview
The Python-Based Employee Management System is an interactive application designed to manage employee information in an organization. The system enables users to store employee details, track performance, and generate reports based on criteria such as department, performance rating, and more. The project integrates fundamental Python programming concepts such as loops, conditional statements, data structures, exception handling, and file handling. This project aims to demonstrate the ability to create a functional, error-resilient application that meets real-world business needs.

**Project Objectives**

The goal of this capstone project is to:

* Develop a Python-based application to manage employee data efficiently.
* Implement a performance tracking system where the application calculates and displays employee performance based on user input.
* Ensure the system can handle invalid inputs gracefully with appropriate error handling mechanisms.
* Allow for report generation based on employee information.

**User Stories**

**User Story 1: Task Prioritization**

As a student or employee manager, I want to organize tasks or employee projects by deadlines and priority so that I can manage the workload efficiently.

**Solution:** The application will allow the user to input employee tasks or projects with deadlines and priority levels. The system will automatically generate a prioritized task list based on the given priority.

**User Story 2: Performance Tracking**

As a student or employee manager, I want to track performance across different tasks or projects to identify areas for improvement and make data-driven decisions.

**Solution:** The application will allow for the input of employee performance scores and automatically calculate averages, flagging areas where improvements can be made.

**Implementation Plan**

**Phase 1: Task Management**
* Develop input methods for employee task details such as task name, priority, and deadline.
* Organize the input data in a way that allows sorting based on priority and deadline.
* Output the sorted tasks with clear labels and formatting.

**Phase 2: Performance Tracking**

* Implement methods to track and store employee scores for different tasks.
* Calculate the average score for each employee and flag areas where performance is below average.
* Allow the user to input feedback for each employee based on performance.

**Phase 3: Error Handling**

* Implement exception handling to handle invalid inputs for task management and performance tracking (e.g., non-numeric scores).
* Provide appropriate feedback and error messages to the user for all invalid operations.
* Enhance application stability by ensuring all errors are logged and handled gracefully.

**Learning Outcomes**

By completing this project, the following skills will be acquired:

* Python Basics: Understanding and using variables, loops, data structures (lists, dictionaries), and conditional statements.
* Error Handling: Applying exception handling mechanisms to catch and manage common errors.
* Modular Programming: Breaking down the program into manageable, reusable functions for clarity and maintainability.
* File Handling: Using Python’s built-in file handling capabilities to store and retrieve data efficiently.
"""

import logging

# Configure logging to track errors
logging.basicConfig(filename='employee_management_log.txt', level=logging.ERROR)

class Employee:
    def __init__(self, name, department, tasks=None, performance_scores=None):
        self.name = name
        self.department = department
        self.tasks = tasks if tasks else []
        self.performance_scores = performance_scores if performance_scores else []

    def add_task(self, task, priority, deadline):
        self.tasks.append({"task": task, "priority": priority, "deadline": deadline})

    def add_performance_score(self, score):
        self.performance_scores.append(score)

    def average_score(self):
        if len(self.performance_scores) == 0:
            return 0
        return sum(self.performance_scores) / len(self.performance_scores)

def display_menu():
    print("\n--- Employee Management System ---")
    print("1. Add Employee")
    print("2. Add Task")
    print("3. Track Performance")
    print("4. View Employee Tasks")
    print("5. View Performance Report")
    print("6. Exit")

def get_number_input(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Invalid input! Please enter a valid number.")

def get_employee_input():
    name = input("Enter employee name: ")
    department = input("Enter employee department: ")
    return Employee(name, department)

def add_employee(employees):
    employee = get_employee_input()
    employees.append(employee)
    print(f"Employee {employee.name} added successfully!")

def add_task(employee):
    task_name = input("Enter task name: ")
    priority = get_number_input("Enter task priority (1-high, 2-medium, 3-low): ")
    deadline = input("Enter task deadline (YYYY-MM-DD): ")
    employee.add_task(task_name, priority, deadline)
    print(f"Task '{task_name}' added to {employee.name}'s schedule.")

def track_performance(employee):
    score = get_number_input(f"Enter performance score for {employee.name}: ")
    employee.add_performance_score(score)
    print(f"Performance score of {score} added for {employee.name}.")

def view_employee_tasks(employee):
    print(f"Tasks for {employee.name}:")
    sorted_tasks = sorted(employee.tasks, key=lambda x: x['priority'])
    for task in sorted_tasks:
        print(f"Task: {task['task']} | Priority: {task['priority']} | Deadline: {task['deadline']}")

def view_performance_report(employee):
    avg_score = employee.average_score()
    print(f"Performance Report for {employee.name}:")
    print(f"Average Score: {avg_score:.2f}")
    if avg_score < 50:
        print("Improvement Needed!")
    else:
        print("Great Performance!")

def main():
    employees = []

    while True:
        display_menu()
        choice = input("Choose an option: ")

        if choice == '1':
            add_employee(employees)
        elif choice == '2':
            name = input("Enter employee name: ")
            employee = next((e for e in employees if e.name == name), None)
            if employee:
                add_task(employee)
            else:
                print("Employee not found.")
        elif choice == '3':
            name = input("Enter employee name: ")
            employee = next((e for e in employees if e.name == name), None)
            if employee:
                track_performance(employee)
            else:
                print("Employee not found.")
        elif choice == '4':
            name = input("Enter employee name: ")
            employee = next((e for e in employees if e.name == name), None)
            if employee:
                view_employee_tasks(employee)
            else:
                print("Employee not found.")
        elif choice == '5':
            name = input("Enter employee name: ")
            employee = next((e for e in employees if e.name == name), None)
            if employee:
                view_performance_report(employee)
            else:
                print("Employee not found.")
        elif choice == '6':
            print("Exiting system. Goodbye!")
            break
        else:
            print("Invalid option. Please try again.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        logging.error(f"An error occurred: {str(e)}")
        print("An error occurred. Please check the log file for more details.")

"""1. **Employee Class:** The Employee class holds employee details, including tasks and performance scores.
* add_task: Adds a task with a given priority and deadline.
* add_performance_score: Adds a performance score for the employee.
* average_score: Calculates the average performance score.

2. **Menu System:** The display_menu function presents options for adding employees, tasks, tracking performance, and viewing reports.

3. **Input Handling:** Functions like get_number_input ensure valid numerical input is provided by users.

4. **Exception Handling:** The try...except block in the main function logs errors to a file if an unexpected error occurs.

5. **Logging:** The logging module is used to track errors that occur during execution, which helps with debugging.

##**Conclusion**
This Python-Based Employee Management System project integrates core programming concepts and tools to create a user-friendly and functional application for managing employee tasks and performance. The use of Python fundamentals, error handling, and modular programming techniques has allowed the development of a stable and maintainable application that meets the needs of businesses looking to track employee data efficiently. Through this capstone project, key skills such as Python programming, error resilience, and file handling have been demonstrated.
"""

