# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5OWYPvA2SQUxa7PdIAph9CiANyICK2L

# **Exploring String Methods**
## By Ajay Sethuraman
## **Introduction**
Strings are one of the most fundamental data types in Python. They offer a variety of methods for manipulation, slicing, and formatting. In this assignment, we’ll explore different string operations through three exciting tasks: slicing, using string methods, and checking for palindromes.

**Task 1 - String Slicing and Indexing**

We will extract specific parts of a string using slicing and indexing.
"""

# Define the string
text = "Python is amazing!"

# Extracting parts using slicing
first_word = text[:6]  # "Python"
amazing_part = text[10:-1]  # "amazing"
reversed_text = text[::-1]  # Reverse the entire string

# Printing the results
print("First word:", first_word)
print("Amazing part:", amazing_part)
print("Reversed string:", reversed_text)

"""**Task 2 - Exploring String Methods**

We will apply common string methods to format and modify a given string.
"""

# Define the string
text = " hello, python world! "

# Applying string methods
stripped_text = text.strip()  # Remove extra spaces
capitalized_text = stripped_text.capitalize()  # Capitalize first letter
replaced_text = stripped_text.replace("world", "universe")  # Replace word
upper_text = stripped_text.upper()  # Convert to uppercase

# Printing results
print("Stripped:", stripped_text)
print("Capitalized:", capitalized_text)
print("Replaced:", replaced_text)
print("Uppercase:", upper_text)

"""**Task 3 - Check for Palindromes**

A palindrome is a word that reads the same forward and backward. We will write a program to check for palindromes.
"""

# Asking for user input
word = input("Enter a word: ").lower()  # Convert to lowercase for consistency

# Check if the word is a palindrome
if word == word[::-1]:
    print(f"Yes, '{word}' is a palindrome! 🎉")
else:
    print(f"No, '{word}' is not a palindrome. ❌")

"""## **Conclusion**
Through this assignment, I explored string slicing, various string methods, and palindrome checking. These operations are powerful tools for text processing and manipulation in Python.
"""